# On utilise une version légère de Python
FROM python:3.9-slim

# Bonnes pratiques : ne pas tourner en root
WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# On expose le port 5000
EXPOSE 5000

# Commande de lancement
CMD ["python", "app.py"]